### PR TITLE
Add Litecoin LTC

### PR DESCRIPTION
**Pull request by PrinceMatthew**
Pull request to add Litecoin on Tixl Finance.

### CODE REVIEW

**Comment by fnnhnsn** [comment]
Hey Matthew, thanks for your PR, it is already looking great! If you'd like, you could add a `description.md` like the [Tixl one](https://github.com/tixlfinance/tixlfinance-community-data/blob/master/projects/tixl-txl/description.md) with a short description in it, which will display in the project tab on the project detail page. 

We're currently still working on an updated version of the project integration flow and are planning to be finished by tomorrow evening and will then merge it.

Best greetings from Hamburg, Finn

**Comment by PrinceMatthew** [comment]
Description has been added, and it's ready to merge!

**Comment by fnnhnsn** [comment]
Thanks a lot, we'll merge it as soon as we're ready!

**Comment by leif-eric93** [comment]
Hi Matthew, 

thanks for the Request. 

I just tested the data with our project data preview tool (which will launch publicly soon) and everything looks great! I will merge your PR right now :)

**Pull request merged**
